trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016' 'windows-2019'


steps:
- script: |
    echo Starting the build
  displayName: 'Build with Maven'
  
- script: |
    echo Starting the build
  displayName: 'Build with only master branch'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
    echo Starting the build
  displayName: 'Build with only master reelase/trial_nuget'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release/trial_nuget'))
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Working' 
  condition: succeededOrFailed()
  
  

- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: wangzSSH
    sourceFolder: '$(Build.SourcesDirectory)\Working'
    targetFolder: '/big/dom/xwangz/azure/gsp_dotnet'
    contents: '*.zip'
    flattenFolders: true
  enabled: false