trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    dotnet --info
  displayName: 'Dotnet installs'


- powershell: |
    .\build.ps1
  displayName: 'Run build'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)/Working'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Working' 
    includeRootFolder: false
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/$gudusoft.gsqlparser.3.0.3.8.zip' 
    replaceExistingArchive: true 
    #verbose: # Optional
    #quiet: # Optional
  