trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    dotnet --info
  displayName: 'Dotnet installs'


- powershell: |
    .\build.ps1
  displayName: 'Run build'
  
  
# Download GitHub Release
# Downloads a GitHub Release from a repository
- task: DownloadGitHubRelease@0
  displayName: 'Download dotnet demo src to $(System.ArtifactsDirectory)'
  inputs:
    connection: dotnet_demo_github
    userRepository: sqlparser/gsp_demo_dotnet.git
    defaultVersionType: latest # Options: latest, specificVersion, specificTag
    #version: # Required when defaultVersionType != Latest
    #itemPattern: '**' # Optional
    downloadPath: '$(System.ArtifactsDirectory)' 
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Working' 
  condition: succeededOrFailed()
  