trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    dotnet --info
  displayName: 'Dotnet installs'


- powershell: |
    .\build.ps1
  displayName: 'Run build'
  
     
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Working' 
  condition: succeededOrFailed()
  